from __future__ import annotations

import re
from pathlib import Path

from speak_swiftly_agent.models import AgentReport
from speak_swiftly_agent.repo import resolve_repo_root

DEFAULT_REPORT_DIR = Path("docs") / "agents" / "reports"


def report_slug(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "report"


def resolve_report_dir(repo_root: Path, report_dir: Path | None = None) -> Path:
    root = resolve_repo_root(repo_root)
    requested_dir = report_dir or DEFAULT_REPORT_DIR
    if requested_dir.is_absolute():
        return requested_dir
    return root / requested_dir


def write_agent_report(
    repo_root: Path,
    task: str,
    report: AgentReport,
    report_dir: Path | None = None,
) -> Path:
    directory = resolve_report_dir(repo_root, report_dir)
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"{report_slug(task)}.md"
    path.write_text(report_document(report), encoding="utf-8")
    return path


def report_document(report: AgentReport) -> str:
    return (
        "<!-- Generated by SpeakSwiftlyAgent. Re-run the agent to refresh this report. -->\n\n"
        f"{report.as_markdown()}"
    )
